name: Deploy FastAPI Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} <<-'EOF'
            
            # Ensure make is installed
            if ! command -v make &> /dev/null; then
                echo "Installing make..."
                sudo yum install -y make
            fi
            
            # Define variables
            DEPLOY_DIR="/home/ec2-user/FinancialModelling"

            # Clone or update repository
            if [ ! -d "$DEPLOY_DIR" ]; then
                echo "Cloning repository..."
                git clone https://github.com/SammySho/FinancialModelling.git "$DEPLOY_DIR"
            else
                echo "Updating repository..."
                cd "$DEPLOY_DIR"
                git reset --hard HEAD
                git clean -fd
                git fetch origin
                git reset --hard origin/main
            fi

            # Set up environment variables
            cd "$DEPLOY_DIR"
            echo "DB_URL=${{ secrets.DB_URL }}" > backend/.env
            echo "DB_KEY=${{ secrets.DB_KEY }}" >> backend/.env

            # Run deployment using Make
            cd backend
            make all
          EOF
